### ISSUE TITLE
Should be AGPL-3.0

### ISSUE THREAD

**Issue by BlueGlassBlock** [Rainbow-Project/bot_rain_py#4]

**Comment by Redlnn** [comment]
Mirai & Graia 项目都应使用 **AGPL-3.0 协议** 而不是 GPL-3.0

**Comment by Int-0X7FFFFFFF** [comment]
我对我的失误十分抱歉
这个仓库的所以内容依然在完善的过程中
您所指出的问题现在已经得到修正
由于时间有限其他的部分的完善会在未来逐步完成
